import os
import re
import json
import string
from groq import Groq

_client: Groq | None = None


def _get_client() -> Groq:
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client

LLM_WEIGHT = 0.6
STYLO_WEIGHT = 0.4
CONFIDENCE_THRESHOLD = 0.75  # matches spec.md § Confidence Thresholds

_SYSTEM_PROMPT = """You are a forensic text analyst specializing in detecting whether content \
was written by a human or generated by an AI system.

Analyze the provided text for:
- Stylistic coherence: Does the writing feel consistent or artificially uniform?
- Semantic naturalness: Are word choices and transitions human-like or optimized?
- Structural patterns: Does the text show AI tendencies (e.g. formulaic structure, \
over-explanation, hedging language)?

Return a JSON object with exactly two fields:
  "result": either "ai" or "human"
  "confidence": a float between 0.0 and 1.0 representing your certainty (1.0 = fully certain)

Only return the JSON object, nothing else."""


def classify_with_llm(text: str) -> dict:
    """
    Signal 1 — LLM classification.
    Returns: { result: "ai"|"human", llm_score: float, weight: float }
    """
    response = _get_client().chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": f"Classify the following text:\n\n{text}"},
        ],
        response_format={"type": "json_object"},
        temperature=0.1,
    )

    parsed = json.loads(response.choices[0].message.content)

    result = parsed.get("result", "human").lower()
    if result not in ("ai", "human"):
        result = "human"

    return {
        "result": result,
        "llm_score": float(parsed.get("confidence", 0.5)),
        "weight": LLM_WEIGHT,
    }


# ------------------------------------------------------------
# Signal 2 — Stylometric heuristics
# ------------------------------------------------------------

def _sentence_length_variance(text: str) -> float:
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
    if len(sentences) < 2:
        return 0.0
    lengths = [len(s.split()) for s in sentences]
    mean = sum(lengths) / len(lengths)
    return sum((l - mean) ** 2 for l in lengths) / len(lengths)


def _type_token_ratio(text: str) -> float:
    words = re.findall(r"\b\w+\b", text.lower())
    if not words:
        return 0.0
    return len(set(words)) / len(words)


def _punctuation_density(text: str) -> float:
    if not text:
        return 0.0
    return sum(1 for c in text if c in string.punctuation) / len(text)


def classify_with_stylometrics(text: str) -> dict:
    """
    Signal 2 — Stylometric heuristics.

    Each metric is mapped to an AI-likelihood score (0 = human, 1 = AI):
      - sentence_length_variance: low variance → uniform → AI-like
      - type_token_ratio:         high TTR → diverse vocabulary → AI-like
      - punctuation_density:      high density → structured → AI-like

    Returns: { result, style_score, weight, metrics }
    """
    variance = _sentence_length_variance(text)
    ttr = _type_token_ratio(text)
    density = _punctuation_density(text)

    # Variance: /60 so that human-typical variance (~45) scores below 0.5
    variance_score = max(0.0, min(1.0, 1.0 - variance / 60.0))
    # TTR: baseline 0.75 — short texts always exceed 0.4, so the old baseline gave 1.0 everywhere
    ttr_score      = max(0.0, min(1.0, (ttr - 0.75) / 0.20))
    # Density: baseline 0.005 so typical prose (0.007–0.025) produces meaningful signal
    density_score  = max(0.0, min(1.0, (density - 0.005) / 0.020))

    # Variance carries the most weight on short texts; TTR is weakest
    style_score = 0.5 * variance_score + 0.2 * ttr_score + 0.3 * density_score

    return {
        "result": "ai" if style_score > 0.5 else "human",
        "style_score": round(style_score, 4),
        "weight": STYLO_WEIGHT,
        "metrics": {
            "sentence_length_variance": round(variance, 4),
            "type_token_ratio": round(ttr, 4),
            "punctuation_density": round(density, 4),
        },
    }


# ------------------------------------------------------------
# Confidence scorer
# ------------------------------------------------------------

def compute_confidence(llm_result: dict, stylo_result: dict) -> dict:
    """
    Combine both signals into a single attribution + confidence score.

    Each signal is converted to an AI-likelihood value (0 = human, 1 = AI)
    then merged via weighted average (LLM 0.6, stylometric 0.4).

    Thresholds from spec.md § Confidence Thresholds:
      combined >= 0.75  →  high-confidence AI
      combined <= 0.25  →  high-confidence human
      otherwise         →  uncertain
    """
    # llm_score is confidence-in-prediction: flip when result is "human"
    llm_ai = llm_result["llm_score"] if llm_result["result"] == "ai" else 1 - llm_result["llm_score"]
    # style_score is already an AI likelihood [0=human, 1=AI]: use directly
    stylo_ai = stylo_result["style_score"]

    combined = LLM_WEIGHT * llm_ai + STYLO_WEIGHT * stylo_ai

    if combined >= CONFIDENCE_THRESHOLD:
        attribution    = "ai"
        confidence_score = combined
    elif combined <= (1 - CONFIDENCE_THRESHOLD):
        attribution    = "human"
        confidence_score = 1 - combined
    else:
        attribution    = "uncertain"
        confidence_score = max(combined, 1 - combined)

    return {
        "attribution":    attribution,
        "confidence_score": round(confidence_score, 4),
        "ai_likelihood":  round(combined, 4),
    }
